---

- name: INIT
  hosts: pddb
  become: false
  gather_facts: no
  tags:
    - init

  tasks:
    - name: Create local temp directory
      shell: "mktemp -d --tmpdir={{ g_base_tmpdir }} --suffix=_pddb"
      delegate_to: 127.0.0.1
      run_once: true
      register: reg_tmpdir

    - set_fact:
        p_tmpdir: "{{ reg_tmpdir.stdout }}"


    - debug: msg="Created directory {{ p_tmpdir }}"
      delegate_to: 127.0.0.1
      run_once: true

    - name: Show Connection Infos
      debug: msg="ansible_host={{ ansible_host }}; ansible_user={{ ansible_user }}"

- name: STOP
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - stop

  tasks:
    - debug:
        msg: "No services to stop"

- name: INSTALL
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - install

  roles:
    - role: ilottery_db_install

- name: DROP_DB
  hosts: pddb
  gather_facts: no
  tags:
    - drop_db

  roles:
    - role: ilottery_db_drop

- name: CREATE_DB
  hosts: pddb
  gather_facts: no
  tags:
    - create_db

  roles:
    - role: ilottery_db_create

- name: UPDATE_DB
  hosts: pddb
  gather_facts: no
  tags:
    - update_db

  roles:
    - role: ilottery_db_update

- name: Export DB
  hosts: pddb
  gather_facts: no
  tags:
    - export_db

  roles:
    - role: ilottery_db_export

- name: START
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - start

  tasks:
    - debug:
        msg: "No services to restart"

  roles:
    - ilottery_db_scratch

- name: CLEAN
  hosts: pddb
  become: false
  gather_facts: no
  tags:
    - clean

  tasks:
    - name: Remove local temp directory
      file:
        path: "{{ p_tmpdir }}"
        state: absent
      delegate_to: 127.0.0.1
      run_once: true
