---

- name: INIT
  hosts: all
  become: false
  gather_facts: yes
  tags:
    - init

  tasks:
    - name: Create local temp directory
      shell: "mktemp -d --tmpdir={{ g_base_tmpdir }} --suffix=_pd-sec-gateway"
      delegate_to: 127.0.0.1
      run_once: true
      register: reg_tmpdir

    - set_fact:
        p_tmpdir: "{{ reg_tmpdir.stdout }}"

    - debug: msg="Created directory {{ p_tmpdir }}"
      delegate_to: 127.0.0.1
      run_once: true

    - name: Show Connection Infos
      debug: msg="ansible_host={{ ansible_host }}; ansible_user={{ ansible_user }}"

- name: STOP
  hosts: ilottery_pd_sec_gateway
  become: true
  gather_facts: no
  tags:
    - stop

  tasks:
    - name: Stop Service
      systemd:
        name: "pd-sec-gateway"
        state: stopped
      ignore_errors: yes

- name: INSTALL
  hosts: ilottery_pd_sec_gateway
  become: true
  # dont set gather_facts to no, we need ansible_hostname variable
  gather_facts: yes
  tags:
    - install

  roles:
    - role: os_config
    - role: ilottery_pd_sec_gateway
      jboss_node_port_offset: 400

- name: START
  hosts: ilottery_pd_sec_gateway
  become: true
  gather_facts: no
  tags:
    - start

  tasks:
    - name: Start Service
      systemd:
        name: "pd-sec-gateway"
        state: restarted
        enabled: yes
        daemon_reload: yes

- name: CLEAN
  hosts: local
  become: false
  gather_facts: no
  tags:
    - clean

  tasks:
    - name: Remove local temp directory
      file:
        path: "{{ p_tmpdir }}"
        state: absent
