---

- name: INIT
  hosts: pddb
  become: false
  gather_facts: no
  tags:
    - init

  tasks:
    - name: Create local temp directory
      shell: "mktemp -d --tmpdir={{ g_base_tmpdir }} --suffix=_pddb"
      delegate_to: 127.0.0.1
      run_once: true
      register: reg_tmpdir

    - set_fact:
        p_tmpdir: "{{ reg_tmpdir.stdout }}"


    - debug: msg="Created directory {{ p_tmpdir }}"
      delegate_to: 127.0.0.1
      run_once: true

    - name: Show Connection Infos
      debug: msg="ansible_host={{ ansible_host }}; ansible_user={{ ansible_user }}"

- name: STOP
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - stop

  tasks:
    - debug:
        msg: "No services to stop"

- name: INSTALL
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - install

  roles:
    - role: ilottery_db_install

- name: DROP_DB
  hosts: pddb
  gather_facts: no
  tags:
    - drop_db

  tasks:
    - name: Running drop
      shell: |
        cd /usr/local/gtech/{{ config_overrides.siteName }}-database-install
        ./drop_db_all.sh {{ config_overrides.siteName }} {{ stage }} abort true
      register: drop_run

    - debug: msg="{{ drop_run.stdout }}"

- name: CREATE_DB
  hosts: pddb
  gather_facts: no
  tags:
    - create_db

  tasks:
    - name: Running create
      shell: |
        cd /usr/local/gtech/{{ config_overrides.siteName }}-database-install
        ./create_db_all.sh {{ config_overrides.siteName }} {{ stage }} abort true {{ config_overrides.databases.jdbc.password }}
      register: create_run

    - debug: msg="{{ create_run.stdout }}"

- name: UPDATE_DB
  hosts: pddb
  gather_facts: no
  tags:
    - update_db

  roles:
    - role: ilottery_db_update

- name: Export DB
  hosts: pddb
  gather_facts: no
  tags:
    - export_db

  tasks:
    - name: Running export scripts
      shell: |
        cd /usr/local/gtech/{{ config_overrides.siteName }}-database-install
        ./delta_db_all_export.sh {{ config_overrides.siteName }} {{ stage }} abort true true
      register: export_run

    - debug: msg="{{ export_run.stdout }}"

- name: START
  hosts: pddb
  become: true
  gather_facts: no
  tags:
    - start

  tasks:
    - debug:
        msg: "No services to restart"

- name: CLEAN
  hosts: pddb
  become: false
  gather_facts: no
  tags:
    - clean

  tasks:
    - name: Remove local temp directory
      file:
        path: "{{ p_tmpdir }}"
        state: absent
      delegate_to: 127.0.0.1
      run_once: true
