---

- name: INIT
  hosts: all
  become: false
  gather_facts: no
  tags:
  - init

  tasks:
  - name: Show Connection Infos
    debug: msg= "ansible_host={{ ansible_host }}; ansible_user={{ ansible_user }}"


- name: Presetup Check
  hosts: all
  become: true
  gather_facts: no

  tags:
    - diskspace

  tasks:
  - name: Disk Space size
    shell: "df --output=pcent /var| awk -F'%' 'NR==2{print $1}'"
    register: size_result

  - name: set fact
    set_fact:
      size: "{{ size_result.stdout }}"

  - name: Filesystem OK
    debug:
      msg: "Disk space ok : {{ size }}%"
    when:   size|int   < 80

  - name: Filesystem to be cleaned
    fail:
      msg: "The disk space is almoust full :{{ size }}%"
    when:  size|int  > 80

- name: Presetup Check
  hosts: all
  become: true
  gather_facts: no

  tags:
    - marker

  tasks:
  - name: Check Marker
    shell: 'DR=/opt/jboss;FAIL=$(test -d $DR && find -L $DR -regex ".+\.failed$");( { test ! -z $FAIL && exit 1; } || exit 0 )'
    register: marker

  - name: Marker OK
    debug:
      msg: "Modules deployed Successfull"
    when: marker.rc == 0

  - name: Marker Failed
    fail:
      msg: "Modules Failed"
    when: marker.rc == 1


- name: CLEAN
  hosts: local
  become: false
  gather_facts: no
  tags:
  - clean

  tasks:
  - name: Output Sanity
    shell: "echo Sanity Check  Done"
