---
- set_fact:
    pd_processes_packages:
      - "{{ config.siteName}}-pd-crm-processes-application-rpm"
      - "{{ config.siteName}}-ilottery-balancing-plugins-application-rpm"
      - "{{ config.siteName}}-igaming-balancing-plugins-application-rpm"
      - "{{ config.siteName}}-plm-application-rpm"
      - "{{ config.siteName}}-pd-jboss-modules-rpm"
    jboss_common_packages:
      - "jolokia-1.3.3-1.x86_64"
      - "nodejs-5.11.1-1nodesource.el7.centos.x86_64"
      - "apr"
      - "openssl"
      - "coreutils"
    pd_processes_main_tpls:
      - "{{ p_tmpdir }}/command-connector.properties.tpl"
      - "{{ p_tmpdir }}/crm-connector-client.properties.tpl"
      - "{{ p_tmpdir }}/crm-processes.properties.tpl"
      - "{{ p_tmpdir }}/esa-configuration-processes.xml.tpl"
      - "{{ p_tmpdir }}/event-processor-jms.properties.tpl"
      - "{{ p_tmpdir }}/nickNameOffensiveWordsValidation.properties.tpl"
      - "{{ p_tmpdir }}/onepay.properties.tpl"
      - "{{ p_tmpdir }}/playercard.properties.tpl"
      - "{{ p_tmpdir }}/wc-proxy-url.properties.tpl"
      - "{{ p_tmpdir }}/esa-configuration-balancing-plugins.xml.tpl"
    pd_processes_ilottery_balancing_tpls:
      - "{{ p_tmpdir }}/este-plugin.properties.tpl"
      - "{{ p_tmpdir }}/txstore-este-plugin.properties.tpl"
      - "{{ p_tmpdir }}/txstore-einstants-plugin.properties.tpl"
    pd_processes_igaming_balancing_tpls:
      - "{{ p_tmpdir }}/sms-plugin.properties.tpl"
    pd_processes_balancing_tpls:
      - "{{ p_tmpdir }}/balancing-plugin-common.properties.tpl"
    pd_processes_plm_tpls:
      - "{{ p_tmpdir }}/esa-configuration-plm.xml.tpl"
      - "{{ p_tmpdir }}/plm.properties.tpl"
      - "{{ p_tmpdir }}/crm-connector-client.properties.tpl"

- name: Install jboss common packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ jboss_common_packages }}"

- name: Remove application packages
  when: install_app == "true"
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ pd_processes_packages }}"

- name: remove jboss autodeploy marker files
  shell: 'find {{ jboss_server_path }}/{{ jboss_node_name }}/deployments/ -type f -regex ".*\.\(dodeploy\|skipdeploy\|isdeploying\|deployed\|failed\|isundeploying\|undeployed\|pending\)" -delete'

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ pd_processes_packages }}"

- name: Fetch templates
  when: install_app == "true"
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/command-connector.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/crm-processes.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/esa-configuration-processes.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/event-processor-jms.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/nickNameOffensiveWordsValidation.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/onepay.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/playercard.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-pd-crm-processes-env-config/src/main/env-config/wc-proxy-url.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-igaming-balancing-plugins-env-config/src/main/env-config/esa-configuration-balancing-plugins.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-igaming-balancing-plugins-env-config/src/main/env-config/balancing-plugins/balancing-plugin-common.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-igaming-balancing-plugins-env-config/src/main/env-config/igaming-balancing-plugins/sms-plugin.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-ilottery-balancing-plugins-env-config/src/main/env-config/ilottery-balancing-plugins/este-plugin.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-ilottery-balancing-plugins-env-config/src/main/env-config/ilottery-balancing-plugins/txstore-este-plugin.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-ilottery-balancing-plugins-env-config/src/main/env-config/ilottery-balancing-plugins/txstore-einstants-plugin.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-plm-env-config/src/main/env-config/plm/plm.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-plm-env-config/src/main/env-config/plm/esa-configuration-plm.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-processes/{{ config.siteName }}-plm-env-config/src/main/env-config/plm/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }

- name: Create /etc/gtech/pd/config/pd-processes/main/balancing-plugins folder
  file:
    path: /etc/gtech/pd/config/pd-processes/main/balancing-plugins
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: "Creating directory structure under {{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: jboss
    group: jboss
    mode: 0775
  with_items:
    - "{{ config.sharedStorePath }}renaissance/balancing/root"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/autoplt"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/autopht"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/einstantEsteAutopht"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/este/wagxfer"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/lottery/claim"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/gms/rstrtdplyr"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/vouchers/out/securepc"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/este/crdsumm/este-trans"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/este/finsumm"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/finxfer"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/txsxfer"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/playerver"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/este/txssumm"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/este/acctsumm"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/este/acctxfer"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/clps/in/este/dayend"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/sms/crdsumm/este-trans"
    - "{{ config.sharedStorePath }}renaissance/databalance/{{ config.siteID }}/clps/in/sms/finsumm"
    - "{{ config.sharedStorePath }}renaissance/application/{{ config.siteID }}/tmp"


- name: "Give right permissions to {{ config.sharedStorePath }}renaissance"
  file:
    path: "{{ config.sharedStorePath }}renaissance"
    state: directory
    owner: jboss
    group: jboss
    mode: 0775
    recurse: true

- name: Parsing pd-processes main templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-processes/main/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_processes_main_tpls }}"

- name: Parsing pd-processes plm templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-processes/main/plm/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_processes_plm_tpls }}"

- name: Parsing pd-processes balancing templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-processes/main/balancing-plugins/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_processes_balancing_tpls }}"

- name: Parsing pd-processes igaming balancing templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-processes/main/igaming-balancing-plugins/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_processes_igaming_balancing_tpls }}"

- name: Parsing pd-processes ilottery balancing templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-processes/main/ilottery-balancing-plugins/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_processes_ilottery_balancing_tpls }}"

 # END products configurations 

- name: Install security limits
  template:
    src: "templates/security/limits.conf"
    dest: "/etc/security/limits.conf"
    mode: 0644
    owner: root
    group: root

- name: Create /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/ dir
  file:
    path: /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Install /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml template
  template:
    src: "templates/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    dest: "/opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: Copying 
  copy:
    src: "files/jbossas/jblogrotate.sh"
    dest: "/etc/jbossas/jblogrotate.sh"
    owner: root
    group: root
    mode: 0755

- name: Install jboss cron logrotation /etc/jbossas/jblogrotate.sh
  when: enable_logremoval
  cron:
    name: "jboss logrotation jblogrotate.sh"
    minute: "0"
    hour: "23"
    user: "root"
    job: "/etc/jbossas/jblogrotate.sh {{ keep_logs_days }}"

- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jboss
    group: jboss
    mode: 0755
  with_items:
    - "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}"
    - "/etc/gtech"
    - "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global"
    - "/etc/gtech/pd/config/pd-global/main"
    - "/etc/gtech/pd/config/{{ instance_name }}/main"

- name: "Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main to /etc/gtech/pd/config/{{ instance_name }}/main"
  file:
    src: "/etc/gtech/pd/config/{{ instance_name }}/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main"
    state: link

- name: "Install /etc/gtech/pd/config/{{ instance_name }}/main/module.xml template"
  template:
    src: "templates/gtech/pd/config/{{ instance_name }}/main/module.xml"
    dest: "/etc/gtech/pd/config/{{ instance_name }}/main/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war to /var/lib/jolokia/jolokia.war"
  file:
    src: "/var/lib/jolokia/jolokia.war"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war"
    state: link

- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: Create hash for jboss mgmt password
  shell: echo "{{ jboss_management_user }}:ManagementRealm:{{ jboss_management_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbosspwd

- set_fact: 
    jboss_real_management_pass: "{{ md5jbosspwd.stdout }}"

- name: Install mgmt-users.properties template
  template:
    src: "templates/configuration/mgmt-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/mgmt-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash for jboss ejb password
  shell: echo "{{ ejbuser }}:ApplicationRealm:{{ ejbpassword }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossejbpwd

- set_fact:
    realejbpassword: "{{ md5jbossejbpwd.stdout }}"

- name: Create hash for jboss jms password
  shell: echo "{{ jms_user }}:ApplicationRealm:{{ jms_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossjmspwd

- set_fact:
    realjmspassword: "{{ md5jbossjmspwd.stdout }}"

- name: Install application-users.properties template
  template:
    src: "templates/configuration/application-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/application-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash forejb-security-realm secret
  shell: echo -n "{{ ejbpassword }}" | base64
  register: forejb_security_realm_secret

- set_fact:
    real_forejb_security_realm_secret: "{{ forejb_security_realm_secret.stdout }}"

- name: Install jboss configuration templates
  template:
    src: "templates/configuration/{{ item }}"
    dest: "/etc/jbossas/{{ instance_name }}/{{ item }}"
    mode: 0644
    owner: jboss
    group: jboss
  with_items:
    - application-roles.properties
    - application-users.properties
    - logging.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: Install jboss configuration file
  template:
    src: "templates/configuration/standalone-full-ha.xml"
    dest: "/etc/jbossas/{{ instance_name }}/standalone-automation-{{ instance_name }}.xml"
    mode: 0644
    owner: jboss
    group: jboss
