---
- set_fact:
    dc_adapter_balancing_plugin_packages:
      - "{{ config.siteName}}-dc-adapter-balancing-plugin-application-rpm"

- name: Remove application packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ dc_adapter_balancing_plugin_packages }}"

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ dc_adapter_balancing_plugin_packages }}"

- name: Create /etc/gtech/pd/config/dc-adapter-balancing-plugin folder
  file:
    path: /etc/gtech/pd/config/dc-adapter-balancing-plugin
    state: directory
    owner: springboot
    group: springboot
    mode: 0755

- name: Create /var/log/dc-adapter-balancing-plugin/ folder
  file:
    path: /var/log/dc-adapter-balancing-plugin
    state: directory
    owner: springboot
    group: springboot
    mode: 0755

- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: create /usr/local/env
  file:
    path: "/usr/local/env"
    state: directory
    mode: 0755

- name: "Install env to /usr/local/env/"
  template:
    src: "env/dc-adapter-balancing-plugin"
    dest: "/usr/local/env/dc-adapter-balancing-plugin"
    owner: "springboot"
    group: "springboot"
    mode: 0755
