---
jboss_version: "7.2.9.1"
jboss_java_version: "pd-java-11-openjdk"
jboss_node_name: "{{ instance_name }}"
jboss_node_user: "jboss"
pdsecgateway_host_list: "{{ groups.ilottery_pd_sec_gateway | map('extract', hostvars, ['jboss_listen_ip']) | list }}"
