---
- set_fact:
    batch_packages:
      - "{{ config.siteName}}-batch-install"
      - "{{ config.siteName}}-batch-application-rpm"
    batch_tpls:
      - "{{ p_tmpdir }}/batch.properties.tpl"
      - "{{ p_tmpdir }}/blacklist.properties.tpl"
      - "{{ p_tmpdir }}/crm-connector-client.properties.tpl"
      - "{{ p_tmpdir }}/jdbc.properties.tpl"
      - "{{ p_tmpdir }}/pam-jdbc.properties.tpl"
      - "{{ p_tmpdir }}/sms-jdbc.properties.tpl"
      - "{{ p_tmpdir }}/vouchers.properties.tpl"


- name: Remove application packages
  when: install_app == "true"
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ batch_packages }}"

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ batch_packages }}"

- name: "Create {{ config.sharedStorePath }}/renaissance/application/{{ config.siteID }}/crm/out"
  file:
    path: "{{ config.sharedStorePath }}/renaissance/application/{{ config.siteID }}/crm/out"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Fetch templates
  when: install_app == "true"
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/batch.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/blacklist.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/jdbc.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/pam-jdbc.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/sms-jdbc.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/batch-rpm/{{ config.siteName }}-batch-env-config/src/main/env-config/vouchers.properties.tpl", dest: "{{ p_tmpdir }}" }


- name: Parsing batch templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/opt/gtech/pd4/batch/conf/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ batch_tpls }}"

 # END products configurations 

