---


- name: Remove old packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items:
    - "{{ config.siteName }}-database-install"
    - "ric_esdb5_dbmaint"

- name: Install new packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "{{ config.siteName }}-database-install-{{ config.ilottery_version }}"
    - "ric_esdb5_dbmaint"
    - "ant-1.9.4-2.el7"

- name: Fetch templates
  fetch:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/config.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/dbinstall-properties.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/dbinstall-properties-balancing.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/dbinstall-properties-subcap.xml.tpl", dest: "{{ p_tmpdir }}" }

- name: Remove old folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/local/gtech/{{ config.siteName }}-database-install/db-install/scripts-out"
    - "/usr/local/gtech/{{ config.siteName }}-common-config/env-config"
    - "/usr/local/gtech/{{ config.siteName }}-database-install/env-config"

- name: Create new folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: 0755
    recurse: yes
  with_items:
    - "/usr/local/gtech/{{ config.siteName }}-database-install"
    - "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/{{ stage }}"
    - "/usr/local/gtech/{{ config.siteName }}-common-config/env-config/{{ stage }}"
    - "/var/log/gtech"


- name: Create schema folders
  file:
    path: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/{{ stage }}/{{ item }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: 0755
    recurse: yes
  with_items: "{{ db_schemas }}"


- name: Add config.xml to common-config
  template:
    src: "{{ p_tmpdir }}/config.xml.tpl"
    dest: "/usr/local/gtech/{{ config.siteName }}-common-config/env-config/{{ stage }}/config.xml"
    mode: 0644
    owner: "{{ ansible_ssh_user }}"

- name: Add dbinstall-properties.xml to all schemas
  template:
    src: "{{ p_tmpdir }}/dbinstall-properties.xml.tpl"
    dest: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/{{ stage }}/{{ item }}/dbinstall-properties.xml"
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
  with_items: "{{ db_schemas }}"

- name: Add dbinstall-properties-balancing.xml to balancing
  template:
    src: "{{ p_tmpdir }}/dbinstall-properties-balancing.xml.tpl"
    dest: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/{{ stage }}/balancing/dbinstall-properties.xml"
    mode: 0644
    owner: "{{ ansible_ssh_user }}"

- name: Add dbinstall-properties-subcap.xml to subcap
  template:
    src: "{{ p_tmpdir }}/dbinstall-properties-subcap.xml.tpl"
    dest: "/usr/local/gtech/{{ config.siteName }}-database-install/env-config/{{ stage }}/subcap/dbinstall-properties.xml"
    mode: 0644
    owner: "{{ ansible_ssh_user }}"
