---
enable_logremoval: true
keep_logs_days: "5"
http_proxy_port: "6666"
ejbuser: "ejb"
ejbpassword: "ejbpass"
tcpping_base_port: 7600
deployment_scanner_interval: 0
max_connections: 200
bind_interface: "0.0.0.0"
box: "pd-crm"
jgroups_udp_mcast_port: "46003"
pd_core_jboss_node_extraopts: []
pd_core_jboss_node_javaopts: "-Dorg.apache.tomcat.util.http.Parameters.MAX_COUNT=2048 -Xms{{ java_memory_min }}m -Xmx{{ java_memory_max }}m -Xmn{{ java_memory_young }}m -verbose:gc -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman -Dorg.jboss.resolver.warning=true -Dorg.jboss.as.logging.per-deployment=false -Djboss.tx.node.id={{ ansible_hostname }}-{{ instance_name }} -Dhawtio.authenticationEnabled=true -Dhawtio.realm=jboss-web-policy -Dhawtio.role=admin -XX:+UseCompressedOops -Xss256k -Dorg.jboss.resolver.warning=true -Dsun.lang.ClassLoader.allowArraySyntax=true -Djgroups.bind_addr={{ jgroups_bind | default (jboss_listen_ip) }} -Desa.proxy.oauth.plugin.base.packages=com.igt.pd.lottery.oauth -Dcom.igt.pd.lottery.oauth.plugin.config=/etc/igt/anywhere/proxy-oauth/oauth-plugins.properties -Desa.proxy.oauth.plugin.dir=/usr/share/igt/aurora/anywhere/proxy-oauth/plugins {{ pd_core_jboss_node_extraopts | join(' ') }} -XX:+HeapDumpOnOutOfMemoryError"
install_app: "true"