---
enable_logremoval: true
keep_logs_days: "5"
http_proxy_port: "6666"
ejbuser: "ejb"
ejbpassword: "ejbpass"
tcpping_base_port: 7600
deployment_scanner_interval: 0
max_connections: 200
bind_interface: "0.0.0.0"
box: "pd-crm"
jgroups_udp_mcast_port: "46003"
