---
- set_fact:
    pd_core_packages:
      - "{{ config.siteName}}-pd-crm-adapter-application-rpm"
      - "{{ config.siteName}}-geo-compliance-persistence-rpm"
      - "{{ config.siteName}}-vouchers-application-rpm"
        #- "{{ config.siteName}}-subcap-application-rpm"
      - "{{ config.siteName}}-txstore-write-application-rpm"
      - "{{ config.siteName}}-pd-backend-bus-application-rpm"
      - "{{ config.siteName}}-pd-jboss-modules-rpm"
      - "{{ config.siteName}}-anywhere-proxy-oauth-rpm"
      - "{{ config.siteName}}-anywhere-proxy-oauth-plugins-rpm"
    jboss_common_packages:
      - "jolokia-1.3.3-1.x86_64"
      - "nodejs-5.11.1-1nodesource.el7.centos.x86_64"
      - "apr"
      - "openssl"
      - "coreutils"

    pd_core_main_subcap_tpls:
      - "{{ p_tmpdir }}/esa-configuration-subcap.xml.tpl"
      - "{{ p_tmpdir }}/subcap.properties.tpl"

- name: Install jboss common packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ jboss_common_packages }}"


- name: Remove application packages
  when: install_app == "true"
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ pd_core_packages }}"

- name: remove jboss autodeploy marker files
  shell: 'find {{ jboss_server_path }}/{{ jboss_node_name }}/deployments/ -type f -regex ".*\.\(dodeploy\|skipdeploy\|isdeploying\|deployed\|failed\|isundeploying\|undeployed\|pending\)" -delete'

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ pd_core_packages }}"

- name: Create subfolders in local p_tmpdir
  file:
    path: "{{ p_tmpdir }}/vouchers"
    state: directory
    mode: 0755
  delegate_to: 127.0.0.1
  become: false
  run_once: true

- name: Create subfolders in local p_tmpdir
  file:
    path: "{{ p_tmpdir }}/vouchers"
    state: directory
    mode: 0755
  delegate_to: 127.0.0.1
  become: false
  run_once: true

- name: Create /etc/gtech/pd/config/pd-core/main/esa-geocompliance folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/esa-geocompliance
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

    #- name: Create /etc/gtech/pd/config/pd-core/main/subcap folder
    #  file:
    #    path: /etc/gtech/pd/config/pd-core/main/subcap
    #    state: directory
    #    owner: jboss
    #    group: jboss
    #    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/txstore-write folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/txstore-write
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/vouchers folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/vouchers
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/igt/anywhere/proxy-oauth folder
  file:
    path: /etc/igt/anywhere/proxy-oauth
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/backendbus folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/backendbus
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/pd-crm-adapter folder
  file:
    path: /etc/igt/anywhere/pd-crm-adapter
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

  #- name: Parsing pd_core_main_subcap templates
  #  when: install_app == "true"
  #  template:
  #    src: "{{ item }}"
  #    dest: "/etc/gtech/pd/config/pd-core/main/subcap/{{ item | basename | regex_replace('\\.tpl$', '') }}"
  #    mode: 0644
  #  with_fileglob: "{{ pd_core_main_subcap_tpls }}"

 # END products configurations 

- name: Install security limits
  template:
    src: "templates/security/limits.conf"
    dest: "/etc/security/limits.conf"
    mode: 0644
    owner: root
    group: root

- name: Create /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/ dir
  file:
    path: /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Install /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml template
  template:
    src: "templates/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    dest: "/opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

# Check if jblogrotate.sh exist
- name: Check if jblogrotate.sh exist
  stat: 
    path: /etc/jbossas/jblogrotate.sh
  register: jblogrotate_stat

- name: Remove file jblogrotate.sh
  file:
    path: /etc/jbossas/jblogrotate.sh
    state: absent
  when: jblogrotate_stat.stat.exists is defined and jblogrotate_stat.stat.exists == true

- name: Remove jboss cron logrotation /etc/jbossas/jblogrotate.sh
  when: enable_logremoval
  cron:
    name: "jboss logrotation jblogrotate.sh"
    state: absent

# - name: Copying 
#   copy:
#     src: "files/jbossas/jblogrotate.sh"
#     dest: "/etc/jbossas/jblogrotate.sh"
#     owner: root
#     group: root
#     mode: 0755

# - name: Install jboss cron logrotation /etc/jbossas/jblogrotate.sh
#   when: enable_logremoval
#   cron:
#     name: "jboss logrotation jblogrotate.sh"
#     minute: "0"
#     hour: "23"
#     user: "root"
#     job: "/etc/jbossas/jblogrotate.sh {{ keep_logs_days }}"

- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jboss
    group: jboss
    mode: 0755
  with_items:
    - "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}"
    - "/etc/gtech"
    - "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global"
    - "/etc/gtech/pd/config/pd-global/main"
    - "/etc/gtech/pd/config/{{ instance_name }}/main"

- name: "Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main to /etc/gtech/pd/config/{{ instance_name }}/main"
  file:
    src: "/etc/gtech/pd/config/{{ instance_name }}/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main"
    state: link


- name: Install /etc/gtech/pd/config/{{ instance_name }}/main/module.xml template
  template:
    src: "templates/gtech/pd/config/{{ instance_name }}/main/module.xml"
    dest: "/etc/gtech/pd/config/{{ instance_name }}/main/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war to /var/lib/jolokia/jolokia.war"
  file:
    src: "/var/lib/jolokia/jolokia.war"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war"
    state: link

- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: Create hash for jboss mgmt password
  shell: echo "{{ jboss_management_user }}:ManagementRealm:{{ jboss_management_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbosspwd

- set_fact: 
    jboss_real_management_pass: "{{ md5jbosspwd.stdout }}"

- name: Install mgmt-users.properties template
  template:
    src: "templates/configuration/mgmt-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/mgmt-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash for jboss ejb password
  shell: echo "{{ ejbuser }}:ApplicationRealm:{{ ejbpassword }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossejbpwd

- set_fact:
    realejbpassword: "{{ md5jbossejbpwd.stdout }}"

- name: Create hash for jboss jms password
  shell: echo "{{ jms_user }}:ApplicationRealm:{{ jms_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossjmspwd

- set_fact:
    realjmspassword: "{{ md5jbossjmspwd.stdout }}"

- name: Create hash forejb-security-realm secret
  shell: echo -n "{{ ejbpassword }}" | base64
  register: forejb_security_realm_secret

- set_fact:
    real_forejb_security_realm_secret: "{{ forejb_security_realm_secret.stdout }}"

- name: Install jboss configuration templates
  template:
    src: "templates/configuration/{{ item }}"
    dest: "/etc/jbossas/{{ instance_name }}/{{ item }}"
    mode: 0644
    owner: jboss
    group: jboss
  with_items:
    - logging.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: Install jboss configuration file
  template:
    src: "templates/configuration/standalone-full-ha.xml"
    dest: "/etc/jbossas/{{ instance_name }}/standalone-automation-{{ instance_name }}.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: create /usr/local/env
  file:
    path: "/usr/local/env"
    state: directory
    owner: "{{ jboss_node_user }}"
    group: "{{ jboss_node_user }}"
    mode: 0755

- name: "delete folder /usr/local/env/{{ jboss_node_name }}"
  file:
    path: "/usr/local/env/{{ jboss_node_name }}"
    state: absent

- name: "Install env to /usr/local/env/{{ jboss_node_name }}"
  template:
    src: "env/pd-core"
    dest: "/usr/local/env/pd-core"
    owner: "{{ jboss_node_user }}"
    group: "{{ jboss_node_user }}"
    mode: 0755
