---
- set_fact:
    pd_core_packages:
      - "{{ config.siteName}}-pd-crm-adapter-application-rpm"
      - "{{ config.siteName}}-geo-compliance-persistence-rpm"
      - "{{ config.siteName}}-vouchers-application-rpm"
        #- "{{ config.siteName}}-subcap-application-rpm"
      - "{{ config.siteName}}-txstore-write-application-rpm"
      - "{{ config.siteName}}-pd-backend-bus-application-rpm"
      - "{{ config.siteName}}-pd-jboss-modules-rpm"
      - "{{ config.siteName}}-anywhere-proxy-oauth-rpm"
      - "{{ config.siteName}}-anywhere-proxy-oauth-plugins-rpm"
    jboss_common_packages:
      - "jolokia-1.3.3-1.x86_64"
      - "nodejs-5.11.1-1nodesource.el7.centos.x86_64"
      - "apr"
      - "openssl"
      - "coreutils"

    pd_core_main_tpls:
      - "{{ p_tmpdir }}/crm-connector-client.properties.tpl"
      - "{{ p_tmpdir }}/crm-connector-tvc.properties.tpl"
      - "{{ p_tmpdir }}/onepay.properties.tpl"
    pd_core_main_vouchers_tpls:
      - "{{ p_tmpdir }}/vouchers/vouchers.properties.tpl"
      - "{{ p_tmpdir }}/vouchers/event-processor-jms.properties.tpl"
      - "{{ p_tmpdir }}/vouchers/esa-configuration-vouchers.xml.tpl"
      - "{{ p_tmpdir }}/vouchers/esa-configuration-vouchers-internal.xml.tpl"
    pd_core_main_subcap_tpls:
      - "{{ p_tmpdir }}/esa-configuration-subcap.xml.tpl"
      - "{{ p_tmpdir }}/subcap.properties.tpl"
    pd_core_main_esa_geocompliance_tpls:
      - "{{ p_tmpdir }}/geo-compliance-adapter.properties.tpl"
      - "{{ p_tmpdir }}/esa-configuration-geocompliance-persistence.xml.tpl"
    pd_core_main_txstore_tpls:
      - "{{ p_tmpdir }}/txstore.properties.tpl"
      - "{{ p_tmpdir }}/txstore-lottery-plugin.properties.tpl"
      - "{{ p_tmpdir }}/esa-configuration-txstore.xml.tpl"
    pd_core_proxy_oauth_tpl:
      - "{{ p_tmpdir }}/esa-gateway-config-proxy-oauth.xml.tpl"
      - "{{ p_tmpdir }}/oauth-plugins.properties.tpl"
    pd_core_main_backendbus_tpls:
      - "{{ p_tmpdir }}/backendbus.properties.tpl"
    pd_core_main_pd_crm_adapter_tpls:
      - "{{ p_tmpdir }}/pd-crm-adapter/esa-configuration-adapter-internal.xml.tpl"
      - "{{ p_tmpdir }}/pd-crm-adapter/esa-configuration-adapter.xml.tpl"
      - "{{ p_tmpdir }}/pd-crm-adapter/crm-adapter.properties.tpl"
      - "{{ p_tmpdir }}/pd-crm-adapter/event-processor-jms.properties.tpl"
      - "{{ p_tmpdir }}/pd-crm-adapter/command-connector.properties.tpl"

- name: Install jboss common packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ jboss_common_packages }}"

- name: Cleanup container
  when: clean_configs == "false"
  file:
    state: "{{ item }}"
    path: "/etc/gtech/pd/config/pd-core/main"
  with_items:
    - absent
    - directory

- name: Remove application packages
  when: install_app == "true"
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ pd_core_packages }}"

- name: remove jboss autodeploy marker files
  shell: 'find {{ jboss_server_path }}/{{ jboss_node_name }}/deployments/ -type f -regex ".*\.\(dodeploy\|skipdeploy\|isdeploying\|deployed\|failed\|isundeploying\|undeployed\|pending\)" -delete'

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ pd_core_packages }}"

- name: Create subfolders in local p_tmpdir
  file:
    path: "{{ p_tmpdir }}/vouchers"
    state: directory
    mode: 0755
  delegate_to: 127.0.0.1
  become: false
  run_once: true

- name: Create subfolders in local p_tmpdir
  file:
    path: "{{ p_tmpdir }}/vouchers"
    state: directory
    mode: 0755
  delegate_to: 127.0.0.1
  become: false
  run_once: true

- name: Fetch templates
  when: install_app == "true"
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/onepay.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/crm-connector-tvc.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/pd-crm-adapter/crm-adapter.properties.tpl", dest: "{{ p_tmpdir }}/pd-crm-adapter" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/pd-crm-adapter/esa-configuration-adapter-internal.xml.tpl", dest: "{{ p_tmpdir }}/pd-crm-adapter" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/pd-crm-adapter/esa-configuration-adapter.xml.tpl", dest: "{{ p_tmpdir }}/pd-crm-adapter" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/pd-crm-adapter/event-processor-jms.properties.tpl", dest: "{{ p_tmpdir }}/pd-crm-adapter" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-crm-adapter-env-config/src/main/env-config/pd-crm-adapter/command-connector.properties.tpl", dest: "{{ p_tmpdir }}/pd-crm-adapter" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-vouchers-env-config/src/main/env-config/vouchers/vouchers.properties.tpl", dest: "{{ p_tmpdir }}/vouchers" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-vouchers-env-config/src/main/env-config/vouchers/event-processor-jms.properties.tpl", dest: "{{ p_tmpdir }}/vouchers" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-vouchers-env-config/src/main/env-config/vouchers/esa-configuration-vouchers.xml.tpl", dest: "{{ p_tmpdir }}/vouchers" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-vouchers-env-config/src/main/env-config/vouchers/esa-configuration-vouchers-internal.xml.tpl", dest: "{{ p_tmpdir}}/vouchers" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-vouchers-env-config/src/main/env-config/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }
      #- { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/esa-configuration-subcap.xml.tpl", dest: "{{ p_tmpdir }}" }
      #- { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/subcap.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-geo-compliance-persistence-env-config/src/main/env-config/esa-geocompliance/geo-compliance-adapter.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-geo-compliance-persistence-env-config/src/main/env-config/esa-geocompliance/esa-configuration-geocompliance-persistence.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-txstore-write-env-config/src/main/env-config/txstore/txstore.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-txstore-write-env-config/src/main/env-config/txstore/txstore-lottery-plugin.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-txstore-write-env-config/src/main/env-config/txstore/esa-configuration-txstore.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-backend-bus-env-config/src/main/env-config/crm-connector-client.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-pd-backend-bus-env-config/src/main/env-config/backendbus/backendbus.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-anywhere-proxy-oauth-env-config/src/main/env-config/esa-gateway-config-proxy-oauth.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/pd-core/{{ config.siteName }}-anywhere-proxy-oauth-env-config/src/main/env-config/oauth-plugins.properties.tpl", dest: "{{ p_tmpdir }}" }

- name: Create /etc/gtech/pd/config/pd-core/main/esa-geocompliance folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/esa-geocompliance
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

    #- name: Create /etc/gtech/pd/config/pd-core/main/subcap folder
    #  file:
    #    path: /etc/gtech/pd/config/pd-core/main/subcap
    #    state: directory
    #    owner: jboss
    #    group: jboss
    #    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/txstore folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/txstore
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/vouchers folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/vouchers
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/igt/anywhere/proxy-oauth folder
  file:
    path: /etc/igt/anywhere/proxy-oauth
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/backendbus folder
  file:
    path: /etc/gtech/pd/config/pd-core/main/backendbus
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Create /etc/gtech/pd/config/pd-core/main/pd-crm-adapter folder
  file:
    path: /etc/igt/anywhere/pd-crm-adapter
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Parsing pd_core_main templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_tpls }}"

- name: Parsing pd_core_main_vouchers templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/vouchers/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_vouchers_tpls }}"

  #- name: Parsing pd_core_main_subcap templates
  #  when: install_app == "true"
  #  template:
  #    src: "{{ item }}"
  #    dest: "/etc/gtech/pd/config/pd-core/main/subcap/{{ item | basename | regex_replace('\\.tpl$', '') }}"
  #    mode: 0644
  #  with_fileglob: "{{ pd_core_main_subcap_tpls }}"

- name: Parsing pd_core_main_esa_geocompliance templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/esa-geocompliance/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_esa_geocompliance_tpls }}"

- name: Parsing pd_core_main_txstore templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/txstore/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_txstore_tpls }}"

- name: Parsing pd_core_proxy_oauth templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/igt/anywhere/proxy-oauth/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_proxy_oauth_tpl }}"

- name: Parsing backendbus templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/backendbus/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_backendbus_tpls }}"

- name: Parsing pd_crm_adapter templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-core/main/pd-crm-adapter/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_main_pd_crm_adapter_tpls }}"

 # END products configurations 

- name: Install security limits
  template:
    src: "templates/security/limits.conf"
    dest: "/etc/security/limits.conf"
    mode: 0644
    owner: root
    group: root

- name: Create /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/ dir
  file:
    path: /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Install /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml template
  template:
    src: "templates/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    dest: "/opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: Copying 
  copy:
    src: "files/jbossas/jblogrotate.sh"
    dest: "/etc/jbossas/jblogrotate.sh"
    owner: root
    group: root
    mode: 0755

- name: Install jboss cron logrotation /etc/jbossas/jblogrotate.sh
  when: enable_logremoval
  cron:
    name: "jboss logrotation jblogrotate.sh"
    minute: "0"
    hour: "23"
    user: "root"
    job: "/etc/jbossas/jblogrotate.sh {{ keep_logs_days }}"

- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jboss
    group: jboss
    mode: 0755
  with_items:
    - "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}"
    - "/etc/gtech"
    - "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global"
    - "/etc/gtech/pd/config/pd-global/main"
    - "/etc/gtech/pd/config/{{ instance_name }}/main"

- name: "Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main to /etc/gtech/pd/config/{{ instance_name }}/main"
  file:
    src: "/etc/gtech/pd/config/{{ instance_name }}/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main"
    state: link


- name: Install /etc/gtech/pd/config/{{ instance_name }}/main/module.xml template
  template:
    src: "templates/gtech/pd/config/{{ instance_name }}/main/module.xml"
    dest: "/etc/gtech/pd/config/{{ instance_name }}/main/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war to /var/lib/jolokia/jolokia.war"
  file:
    src: "/var/lib/jolokia/jolokia.war"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war"
    state: link

- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: Create hash for jboss mgmt password
  shell: echo "{{ jboss_management_user }}:ManagementRealm:{{ jboss_management_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbosspwd

- set_fact: 
    jboss_real_management_pass: "{{ md5jbosspwd.stdout }}"

- name: Install mgmt-users.properties template
  template:
    src: "templates/configuration/mgmt-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/mgmt-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash for jboss ejb password
  shell: echo "{{ ejbuser }}:ApplicationRealm:{{ ejbpassword }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossejbpwd

- set_fact:
    realejbpassword: "{{ md5jbossejbpwd.stdout }}"

- name: Create hash for jboss jms password
  shell: echo "{{ jms_user }}:ApplicationRealm:{{ jms_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossjmspwd

- set_fact:
    realjmspassword: "{{ md5jbossjmspwd.stdout }}"

- name: Install application-users.properties template
  template:
    src: "templates/configuration/application-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/application-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash forejb-security-realm secret
  shell: echo -n "{{ ejbpassword }}" | base64
  register: forejb_security_realm_secret

- set_fact:
    real_forejb_security_realm_secret: "{{ forejb_security_realm_secret.stdout }}"

- name: Install jboss configuration templates
  template:
    src: "templates/configuration/{{ item }}"
    dest: "/etc/jbossas/{{ instance_name }}/{{ item }}"
    mode: 0644
    owner: jboss
    group: jboss
  with_items:
    - application-roles.properties
    - application-users.properties
    - logging.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: Install jboss configuration file
  template:
    src: "templates/configuration/standalone-full-ha.xml"
    dest: "/etc/jbossas/{{ instance_name }}/standalone-automation-{{ instance_name }}.xml"
    mode: 0644
    owner: jboss
    group: jboss
