---
- set_fact:
    pd_core_standalone_packages:
      - "{{ config.siteName}}-subcap-application-rpm"
    pd_core_subcap_tpls:
      - "{{ p_tmpdir }}/additional.properties.tpl"
      - "{{ p_tmpdir }}/logback-spring.xml.tpl"
      - "{{ p_tmpdir }}/esa-configuration-subcap.xml.tpl"
      - "{{ p_tmpdir }}/subcap.properties.tpl"

- name: Remove application packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ pd_core_standalone_packages }}"

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ pd_core_standalone_packages }}"

- name: Change {{ application_working_directory }} ownership, group and permissions
  file:
    path: "{{ application_working_directory }}"
    state: directory
    recurse: yes
    owner: "{{application_user}}"
    group: "{{application_user}}"
    mode: 0775

- name: Change application log folder permissions
  file:
    path: "/var/log/{{application_name}}"
    state: directory
    recurse: yes
    owner: "{{application_user}}"
    group: "{{application_user}}"
    mode: 0775
    
- name: Fetch templates
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/additional.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/esa-configuration-subcap.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/logback-spring.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/subcap.properties.tpl", dest: "{{ p_tmpdir }}" }

- name: Parsing subcap templates
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/subcap/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_subcap_tpls }}"

- name: Create directory for iMarks submission convertion libraries
  file:
    path: "/etc/gtech/pd/config/subcap/lib"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Copy iMarks submission convertion libraries
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  with_items:
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/lib/libGtech-sgi-tn.so", dest: "/etc/gtech/pd/config/subcap/lib" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/lib/libTicketMapper.so", dest: "/etc/gtech/pd/config/subcap/lib" }

- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: create /usr/local/env
  file:
    path: "/usr/local/env"
    state: directory
    mode: 0755

- name: "Install env to /usr/local/env/"
  template:
    src: "env/subcap"
    dest: "/usr/local/env/subcap"
    owner: "springboot"
    group: "springboot"
    mode: 0755
