---
- set_fact:
    pd_core_standalone_packages:
      - "{{ config.siteName}}-subcap-application-rpm"
    pd_core_subcap_tpls:
      - "{{ p_tmpdir }}/additional.properties.tpl"
      - "{{ p_tmpdir }}/logback-spring.xml.tpl"
      - "{{ p_tmpdir }}/esa-configuration-subcap.xml.tpl"
      - "{{ p_tmpdir }}/subcap.properties.tpl"

- name: Remove application packages
  when: install_app == "true"
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ pd_core_standalone_packages }}"

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ pd_core_standalone_packages }}"

- name: Fetch templates
  when: install_app == "true"
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/additional.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/esa-configuration-subcap.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/logback-spring.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/subcap/{{ config.siteName }}-subcap-env-config/src/main/env-config/subcap/subcap.properties.tpl", dest: "{{ p_tmpdir }}" }

- name: Parsing subcap templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/subcap/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ pd_core_subcap_tpls }}"


- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

