---
- set_fact:
    este_gatewat_adapter_packages:
      - "{{ config.siteName}}-este-gateway-adapter-application-rpm"
    jboss_common_packages:
      - "jolokia-1.3.3-1.x86_64"
      - "ric_db2driver-4.19.66-3.noarch"
      - "nodejs-5.11.1-1nodesource.el7.centos.x86_64"
      - "apr"
      - "openssl"
      - "coreutils"
      - "hawtio-no-slf4j-1.4.65-1"
    este_gatewat_adapter_main_tpls:
      - "{{ p_tmpdir }}/esa-configuration-este-gateway-adapter.xml.tpl"
      - "{{ p_tmpdir }}/esaadapter.properties.tpl"
    este_gatewat_adapter_gtech_tpls:
      - "{{ p_tmpdir }}/hist-host.properties.tpl"
      - "{{ p_tmpdir }}/info-host.properties.tpl"
      - "{{ p_tmpdir }}/pay-host.properties.tpl"

- name: Install jboss common packages
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ jboss_common_packages }}"

- name: Remove application packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ este_gatewat_adapter_packages }}"

- name: Install application packages from yum repo
  when: install_app == "true"
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ este_gatewat_adapter_packages }}"

- name: Fetch templates
  when: install_app == "true"
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/este-gateway-adapter/{{ config.siteName }}-este-gateway-adapter-env-config/src/main/env-config/esaadapter/esaadapter.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/este-gateway-adapter/{{ config.siteName }}-este-gateway-adapter-env-config/src/main/env-config/esaadapter/esa-configuration-este-gateway-adapter.xml.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/este-gateway-adapter/{{ config.siteName }}-este-gateway-adapter-env-config/src/main/env-config/este-gateway-adapter/hist-host.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/este-gateway-adapter/{{ config.siteName }}-este-gateway-adapter-env-config/src/main/env-config/este-gateway-adapter/info-host.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/este-gateway-adapter/{{ config.siteName }}-este-gateway-adapter-env-config/src/main/env-config/este-gateway-adapter/pay-host.properties.tpl", dest: "{{ p_tmpdir }}" }


- name: Parsing este-gatewat-adapter main templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/este-gateway-adapter/main/esaadapter{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ este_gatewat_adapter_main_tpls }}"

- name: Parsing este-gatewat-adapter gtech templates
  when: install_app == "true"
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/este-gateway-adapter/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ este_gatewat_adapter_gtech_tpls }}"

 # END products configurations 

- name: Install security limits
  template:
    src: "templates/security/limits.conf"
    dest: "/etc/security/limits.conf"
    mode: 0644
    owner: root
    group: root

- name: Create /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/ dir
  file:
    path: /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0
    state: directory
    owner: jboss
    group: jboss
    mode: 0755

- name: Install /opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml template
  template:
    src: "templates/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    dest: "/opt/jboss/modules/system/layers/base/javax/validation/api/1.1.0/module.xml"
    mode: 0644
    owner: jboss
    group: jboss

- name: Copying 
  copy:
    src: "files/jbossas/jblogrotate.sh"
    dest: "/etc/jbossas/jblogrotate.sh"
    owner: root
    group: root
    mode: 0755

- name: Install jboss cron logrotation /etc/jbossas/jblogrotate.sh
  when: enable_logremoval
  cron:
    name: "jboss logrotation jblogrotate.sh"
    minute: "0"
    hour: "23"
    user: "root"
    job: "/etc/jbossas/jblogrotate.sh {{ keep_logs_days }}"

- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jboss
    group: jboss
    mode: 0755
  with_items:
    - "/etc/gtech/pd/config/{{ instance_name }}/main"
    - "/etc/gtech/pd/config/{{ instance_name }}/main/esaadapter"
    - "/etc/gtech"
    - "/etc/gtech/este-gateway-adapter"

- name: "Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main to /etc/gtech/pd/config/{{ instance_name }}/main"
  file:
    src: "/etc/gtech/pd/config/{{ instance_name }}/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/{{ instance_name }}/main"
    state: link


- name: "Install /etc/gtech/pd/config/{{ instance_name }}/main/module.xml template"
  template:
    src: "templates/gtech/pd/config/{{ instance_name }}/main/module.xml"
    dest: "/etc/gtech/pd/config/{{ instance_name }}/main/module.xml"
    mode: 0644
    owner: jboss
    group: jboss


- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/db2jcc4.jar to /usr/share/java/db2jcc4.jar"
  file:
    src: "/usr/share/java/db2jcc4.jar"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/db2jcc4.jar"
    state: link

- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war to /var/lib/jolokia/jolokia.war"
  file:
    src: "/var/lib/jolokia/jolokia.war"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/jolokia.war"
    state: link

- name: "Create symlinks /usr/share/jbossas/{{ instance_name }}/deployments/essdk-connector.rar to /usr/share/java/essdk-connector.rar"
  file:
    src: "/usr/share/java/essdk-connector.rar"
    dest: "/usr/share/jbossas/{{ instance_name }}/deployments/essdk-connector.rar"
    state: link


- name: Create symlinks /opt/jdk to /usr/lib/jvm/java
  file:
    src: "/usr/lib/jvm/java"
    dest: "/opt/jdk"
    state: link

- name: Create hash for jboss mgmt password
  shell: echo "{{ jboss_management_user }}:ManagementRealm:{{ jboss_management_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbosspwd

- set_fact: 
    jboss_real_management_pass: "{{ md5jbosspwd.stdout }}"

- name: Install mgmt-users.properties template
  template:
    src: "templates/configuration/mgmt-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/mgmt-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash for jboss ejb password
  shell: echo "{{ ejbuser }}:ApplicationRealm:{{ ejbpassword }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossejbpwd

- set_fact:
    realejbpassword: "{{ md5jbossejbpwd.stdout }}"

- name: Create hash for jboss jms password
  shell: echo "{{ jms_user }}:ApplicationRealm:{{ jms_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbossjmspwd

- set_fact:
    realjmspassword: "{{ md5jbossjmspwd.stdout }}"

- name: Create hash for jboss hawtio password
  shell: echo "{{ hawtio_user }}:ApplicationRealm:{{ hawtio_pass }}" | md5sum | cut -d ' ' -f 1
  register: md5jbosshawtiopwd

- set_fact:
    realhawtiopassword: "{{ md5jbosshawtiopwd.stdout }}"

- name: Install application-users.properties template
  template:
    src: "templates/configuration/application-users.properties"
    dest: "/etc/jbossas/{{ instance_name }}/application-users.properties"
    mode: 0644
    owner: jboss
    group: jboss

- name: Create hash forejb-security-realm secret
  shell: echo -n "{{ ejbpassword }}" | base64
  register: forejb_security_realm_secret

- set_fact:
    real_forejb_security_realm_secret: "{{ forejb_security_realm_secret.stdout }}"

- name: Install jboss configuration templates
  template:
    src: "templates/configuration/{{ item }}"
    dest: "/etc/jbossas/{{ instance_name }}/{{ item }}"
    mode: 0644
    owner: jboss
    group: jboss
  with_items:
    - application-roles.properties
    - application-users.properties
    - logging.properties
    - mgmt-groups.properties
    - mgmt-users.properties

- name: Install jboss configuration file
  template:
    src: "templates/configuration/standalone-full-ha.xml"
    dest: "/etc/jbossas/{{ instance_name }}/standalone-automation-{{ instance_name }}.xml"
    mode: 0644
    owner: jboss
    group: jboss
