---
- set_fact:
    global_config_packages:
      - "{{ config.siteName}}-global-config-rpm"
    global_config_tpls:
      - "{{ p_tmpdir }}/activemq.properties.tpl"
      - "{{ p_tmpdir }}/encryption.properties.tpl"
      - "{{ p_tmpdir }}/hsm.properties.tpl"
      - "{{ p_tmpdir }}/tivoli.properties.tpl"
      - "{{ p_tmpdir }}/walletparameters.properties.tpl"
      - "{{ p_tmpdir }}/gaming-engine.properties.tpl"

- name: Remove application packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ global_config_packages }}"

- name: Install application packages from yum repo
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}-1"
    state: present
    disable_gpg_check: yes
  with_items: "{{ global_config_packages }}"


- name: Fetch templates
  fetch:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}/"
    flat: yes
  become: false
  run_once: true
  with_items:
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/activemq.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/encryption.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/hsm.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/tivoli.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/walletparameters.properties.tpl", dest: "{{ p_tmpdir }}" }
    - { src: "/usr/local/gtech/{{ config.siteName }}-global-config/{{ config.siteName }}-global-config/src/main/env-config/gaming-engine.properties.tpl", dest: "{{ p_tmpdir }}" }

- name: Parsing global-config templates
  template:
    src: "{{ item }}"
    dest: "/etc/gtech/pd/config/pd-global/main/{{ item | basename | regex_replace('\\.tpl$', '') }}"
    mode: 0644
  with_fileglob: "{{ global_config_tpls }}"

- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global"

- name: Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/pd-global/main to /etc/gtech/pd/config/pd-global/main
  file:
    src: "/etc/gtech/pd/config/pd-global/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global/main"
    state: link

- name: Install /etc/gtech/pd/config/pd-global/main/module.xml template
  template:
    src: "templates/gtech/pd/config/pd-global/main/module.xml"
    dest: "/etc/gtech/pd/config/pd-global/main/module.xml"
    mode: 0644
