---
- set_fact:
    global_config_packages:
      - "{{ config.siteName}}-global-config-rpm"

- name: Remove application packages
  yum:
    name: "{{ item }}"
    state: removed
    disable_gpg_check: yes
  with_items: "{{ global_config_packages }}"

- name: Launch yum clean all
  shell: "yum clean all"
  become: yes

- name: Install application packages from yum repo
  yum:
    name: "{{ item }}-{{ config.ilottery_version}}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ global_config_packages }}"


- name: Setting correct permissions/ownership on various directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global"

- name: Create symlinks /usr/share/jbossas/modules/com/gtech/pd/config/pd-global/main to /etc/gtech/pd/config/pd-global/main
  file:
    src: "/etc/gtech/pd/config/pd-global/main"
    dest: "/usr/share/jbossas/modules/com/gtech/pd/config/pd-global/main"
    state: link

- name: Install /etc/gtech/pd/config/pd-global/main/module.xml template
  template:
    src: "templates/gtech/pd/config/pd-global/main/module.xml"
    dest: "/etc/gtech/pd/config/pd-global/main/module.xml"
    mode: 0644
